import { parseUserStringFromRegexService } from "./src/regexMatcherService"

const testCases = [
 "What is the visitor count for today?"
, "Give me a list of sources for last month."
, "What is the bounce rate from Google search for this week?"
, "How many events were there yesterday?"
, "Show me the top five pages by pageviews between Monday and Friday last week."
, "What is the visitor count for last week?"
, "Show me a list of browsers for this month."
, "How many visits did we get from social media yesterday?"
, "Give me the top 10 pages by pageviews for this month."
, "What is the bounce rate from email campaigns for last month?"
, "How many events were there on Monday?"
, "What is the conversion rate from Google Ads for today?"
, "Give me a list of utm sources for last year."
, "How many visitors did we get from the US last month?"
, "Show me the top 5 events by count for this week."
, "What is the pageview count for last month?"
, "Give me a list of devices for today."
, "How many visits did we get from Canada yesterday?"
, "What is the bounce rate from Google search for last week?"
, "Show me the top 20 pages by pageviews for last month."
, "What is the conversion rate from Facebook Ads for this month?"
, "Give me a list of referrers for yesterday."
, "How many visitors did we get from social media last month?"
, "What is the event count for yesterday?"
, "Show me a breakdown of events by source for this week."
, "What is the page count for today?"
, "Give me a list of operating systems for last month."
, "How many visits did we get from organic search yesterday?"
, "What is the bounce rate from Google Ads for this month?"
, "Show me the top 15 pages by pageviews for yesterday."
, "What is the conversion rate from Twitter Ads for last month?"
, "Give me a list of utm mediums for today."
, "How many visitors did we get from the UK last month?"
, "What is the event count for last week?"
, "Show me a breakdown of events by source for last month."
, "What is the pageview count for yesterday?"
, "Give me a list of browsers for last month."
, "How many visits did we get from the US yesterday?"
, "What is the bounce rate from email campaigns for this month?"
, "Show me the top 25 pages by pageviews for this week."
, "What is the conversion rate from LinkedIn Ads for yesterday?"
, "Give me a list of referrers for last month."
, "How many visitors did we get from email campaigns last month?"
, "What is the event count for yesterday?"
, "Show me a breakdown of events by source for yesterday."
, "What is the page count for yesterday?"
, "Give me a list of devices for last month."
, "How many visits did we get from Australia yesterday?"
, "What is the bounce rate from Twitter Ads for last month?"
, "Show me the top 30 pages by pageviews for last month."
, "What is the conversion rate from Instagram Ads for this week?"
, "Give me a list of utm sources for today."
, "How many visitors did we get from social media yesterday?"
, "What is the event count for last month?"
, "Show me a breakdown of events by source for last week."
]

parseUserStringFromRegexService(process.argv[2] ?? '')

// console.log(testCases.map(tc => parseUserStringFromRegexService(tc)))